---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/18 10:44
---


LoginView = {}
local this = LoginView

local transform
local gameobject

print("LoginView.lua.txt");

function LoginView.awake(go)
    transform = go.transform
    gameobject = go;
end

function  LoginView.start()
    print("LoginView:start")
  
end

function  LoginView.update()

end

function  LoginView.ondestroy()

end


function LoginView.open(tb)
	print("call back LoginView.open");
end

function LoginView.AccLoginPanel()
	print("显示账号登陆界面")
	goAccLoginPanel = transform:Find("bg/accLogin").gameObject
	goAccLoginPanel:SetActive(true)
end
	



