---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/23 9:03
---

EnumNetEvent = {
    Common = 0,
}

EnumCommon = {
    WXLogin = 0,--微信登录
    QQLogin = 1,--QQ登录
    CMLogin = 2,--游客登录

    Login_Success = 100,
    Login_Failure = 101
}
