---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/17 16:07
---

--CS.GApp.UIMgr:Open("LoginView")
--CS.GApp.UIMgr:UIMgrHello()
print("i am main lua")